servers:
  - key: qlash-br-1
    name: Qlash Brazil 1
    address: qw.qlash.com.br:28501
    enabled: true
    timeout_seconds: 10
  - key: ilha-pent-1
    name: Ilha Pent 1
    address: pent.quakeworld.com.br:28501
    enabled: true
    timeout_seconds: 10
  - key: ilha-quad-0
    name: Ilha Quad 0
    address: quad.quakeworld.com.br:27500
    enabled: true
    timeout_seconds: 10
  - key: ilha-ring-0
    name: Ilha Ring 0
    address: ring.quakeworld.com.br:27500
    enabled: true
    timeout_seconds: 10
