server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location ~ ^/v2/servers/[^/]+/lastscores$ {
        try_files /lastscores.json =404;
    }

    location ~ ^/v2/servers/[^/]+/laststats$ {
        try_files /laststats.json =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
